// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npdqewhdfextydxzertz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZHFld2hkZmV4dHlkeHplcnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDQxMjUsImV4cCI6MjA2MTMyMDEyNX0.mqQmQ3d50dnCeto0Au5NphvAU8ThOg2DkCJM-H-q97w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);